d_scaler:
  id: numpy_minmax_scaler
  feature_range: &id001
  - -1
  - 1
detector_parser:
  id: aidapt_numpy_reader_v0
  filepaths:
  - ./data/realistic_detector/realistic_detector_0.npy
  - ./data/realistic_detector/realistic_detector_1.npy
  - ./data/realistic_detector/realistic_detector_2.npy
  - ./data/realistic_detector/realistic_detector_3.npy
lab2inv: 
  id: lab_variables_to_invariants
  MP: 0.93827
model:
  id: tf_outer_cgan_v0
  unfolding_id: tf_cgan_v0
  unfolding_path: ./innerGAN_model
  batch_size: 4096
  discriminator_layers:
  - - Dense
    - units: 256
  - - LeakyReLU
    - negative_slope: 0.2
  - - Dense
    - units: 128
  - - LeakyReLU
    - negative_slope: 0.2
  - - Dense
    - units: 64
  - - LeakyReLU
    - negative_slope: 0.2
  discriminator_optimizer:
  - Adam
  - beta_1: 0.5
    learning_rate: 1.0e-05
  epochs: 2
  generator_layers:
  - - Dense
    - units: 64
  - - LeakyReLU
    - negative_slope: 0.2
  - - BatchNormalization
    - momentum: 0.8
  - - Dense
    - units: 128
  - - LeakyReLU
    - negative_slope: 0.2
  - - BatchNormalization
    - momentum: 0.8
  - - Dense
    - units: 256
  - - LeakyReLU
    - negative_slope: 0.2
  - - BatchNormalization
    - momentum: 0.8
  generator_optimizer:
  - Adam
  - beta_1: 0.5
    learning_rate: 5.0e-05
  image_shape: 4
  label_shape: 5
  latent_dim: 100
v_scaler:
  id: numpy_minmax_scaler
  feature_range: *id001
vertex_parser:
  id: aidapt_numpy_reader_v0
  filepaths:
  - ./data/realistic_vertex/realistic_vertex_0.npy
  - ./data/realistic_vertex/realistic_vertex_1.npy
  - ./data/realistic_vertex/realistic_vertex_2.npy
  - ./data/realistic_vertex/realistic_vertex_3.npy
driver:
  save_path: ${hydra:runtime.output_dir}
